Partial-bug: #1642373 Changes to support docker containers in server-manager 1. Add packages from pip repo as part of the server-manager-installer. These packages will be used to create a local pip repository on the server-manager node 2. Add dependencies for the server-manager package so that docker-engine/ansible and related packages are installed when installing server-manager 3. Change the setup script to start a docker registry on the server-manager node
NOTE: The feature is still not enabled. It will be enabled in a further commit to
the contrail-server-manager repo

Change-Id: I0514c32a586138471869bf9a64783df01ebd1baf

diff --git a/common/debian/contrail-server-manager-lite/debian/rules b/common/debian/contrail-server-manager-lite/debian/rules
--- a/common/debian/contrail-server-manager-lite/debian/rules
+++ b/common/debian/contrail-server-manager-lite/debian/rules
@@ -12,6 +12,7 @@ SPEC_DIR := $(shell pwd)
 export SB_TOP := $(shell pwd | sed -re "s/\/build\/debian\/contrail-server-manager-lite//g")
 export BUILDTIME := $(shell date -u +%y%m%d%H%M)
 export src_path := $(SB_TOP)/tools/contrail-server-manager/src/
+export ansible_path := $(SB_TOP)/tools/ansible/
 #export src_path := /build/pmiriyala/r22_smlite_1/src/
 export build_root := $(SB_TOP)/build/debian/contrail-server-manager-lite/debian/contrail-server-manager-lite
 export contrail_provisioning_path := $(SB_TOP)/tools/provisioning/contrail_provisioning
@@ -40,6 +41,12 @@ else
 pkg_file := $(src_path)/../../../tools/packaging/tools/scripts/server-manager-thirdparty
 endif
 
+ifdef PIP_PKG_FILE
+	pip_pkg_file :=  $(_pkgFile)
+else
+	pip_pkg_file := $(src_path)/../../../tools/packaging/tools/scripts/server-manager-thirdparty-pip
+endif
+
 ifdef CENTOS_PKT_FILE
 centos_pkg_file := $(_centosPkgFile)
 else
@@ -55,7 +62,7 @@ endif
 ifdef PKG_DIRS
 pkg_sources := $(_pkgDirs)
 else
-pkg_sources := /cs-shared/builder/cache/$(os_ver)/server-manager/
+pkg_sources := /cs-shared/builder/cache/$(os_ver)/server-manager/ /cs-shared/builder/cache/$(os_ver)/server-manager/pip
 endif
 
 
@@ -77,16 +84,23 @@ override_dh_auto_install:
 	install -d -m 754 $(build_root)/etc/contrail_smgr/images/
 	install -d -m 754 $(build_root)/etc/contrail_smgr/contrail-centos-repo/
 	install -d -m 754 $(build_root)/etc/contrail_smgr/contrail-redhat-repo/
+	install -d -m 754 $(build_root)/etc/ansible/
 	install -d -m 754 $(build_root)/usr/sbin/
 	install -d -m 755 $(build_root)/usr/lib/$(python_dir)/dist-packages/cobbler/modules/
 	install -d -m 755 $(build_root)/opt/contrail/server_manager/reprepro/
 	install -d -m 755 $(build_root)/opt/contrail/server_manager/reprepro/dpdk_depends_conf
 	install -d -m 755 $(build_root)/opt/contrail/server_manager/reprepro/conf
+	install -d -m 755 $(build_root)/opt/contrail/server_manager/ansible/
+	install -d -m 755 $(build_root)/opt/contrail/server_manager/ansible/playbooks/
+	install -d -m 755 $(build_root)/opt/contrail/server_manager/ansible/playbooks/contrail-ansible/
+	install -d -m 755 $(build_root)/opt/contrail/server_manager/ansible/playbooks/contrail-ansible/contrailctl
+	install -d -m 755 $(build_root)/opt/contrail/server_manager/ansible/plugins
 	install -d -m 755 $(build_root)/var/www/html/kickstarts/
 	install -d -m 755 $(build_root)/var/www/html/contrail/
 	install -d -m 755 $(build_root)/var/www/html/contrail/images/
 	install -d -m 755 $(build_root)/var/www/html/contrail/config_file/
 	install -d -m 755 $(build_root)/var/www/html/thirdparty_packages/
+	install -d -m 755 $(build_root)/var/www/html/thirdparty_packages/pip_repo
 	install -d $(build_root)/var/log/contrail-server-manager/provision/
 	install -d -m 755 $(build_root)/etc/mail/
 	# Copy/install files
@@ -98,6 +112,12 @@ override_dh_auto_install:
 	scons -U install_contrail_sm_monitoring --root=${build_root}
 	scons -U install_contrail_sm_inventory --root=${build_root}
 	cp -r $(src_path)/*.py $(build_root)/opt/contrail/server_manager/
+	cp -r $(src_path)/ansible/* $(build_root)/opt/contrail/server_manager/ansible/
+	install -p -m 755 $(src_path)/ansible/sm_ansible_server.py $(build_root)/opt/contrail/server_manager/ansible/sm_ansible_server.py
+	cp -r $(src_path)/ansible/plugins/*   $(build_root)/opt/contrail/server_manager/ansible/plugins/
+	if [ -d $(ansible_path) ]; then \
+	    cp -r $(ansible_path)/playbooks/* $(build_root)/opt/contrail/server_manager/ansible/playbooks/contrail-ansible/. ; \
+	fi
 	cp -r $(src_path)/vmware/esxi_contrailvm.py $(build_root)/opt/contrail/server_manager/
 	cp -r $(src_path)/server_mgr_mon_base_plugin.py $(build_root)/opt/contrail/server_manager/
 	cp -r $(src_path)/role_sequence.json $(build_root)/etc/contrail_smgr/
@@ -113,6 +133,7 @@ override_dh_auto_install:
 	install -p -m 755 $(src_path)/ntp.conf.sample $(build_root)/etc/contrail_smgr/ntp.conf.sample
 	cp -r $(src_path)/contrail-server-manager.u $(build_root)/etc/init.d/contrail-server-manager
 	cp -r $(src_path)/contrail-server-manager-lite.start.u  $(build_root)/usr/sbin/contrail-server-manager
+	cp -r $(src_path)/contrail-server-manager-ansible.start.u  $(build_root)/usr/sbin/contrail-server-manager-ansible
 	cp -r $(src_path)/puppet  $(build_root)/etc/contrail_smgr/
 	cp -r $(src_path)/kickstarts  $(build_root)/etc/contrail_smgr/
 	install -p -m 755 $(contrail_provisioning_path)/common/staticroute_setup.py \
@@ -120,6 +141,9 @@ $(build_root)/etc/contrail_smgr/kickstarts/staticroute_setup.py
 	
 	$(src_path)/../../../tools/packaging/tools/scripts/copy_thirdparty_packages.py --package-file $(pkg_file) \
  --destination-dir $(build_root)/var/www/html/thirdparty_packages \
+ --source-dirs $(pkg_sources) || (echo "Copying Built packages failed"; exit 1)
+	$(src_path)/../../../tools/packaging/tools/scripts/copy_thirdparty_packages.py --package-file $(pip_pkg_file) \
+ --destination-dir $(build_root)/var/www/html/thirdparty_packages/pip_repo \
  --source-dirs $(pkg_sources) || (echo "Copying Built packages failed"; exit 1)
 	$(src_path)/../../../tools/packaging/tools/scripts/copy_thirdparty_packages.py --package-file $(centos_pkg_file) \
  --destination-dir $(build_root)/etc/contrail_smgr/contrail-centos-repo \
