there are instances where supervisord start failed, adding code to check if someone else is listening on the server ports

diff --git a/common/control_files/supervisor-vrouter.initd b/common/control_files/supervisor-vrouter.initd
--- a/common/control_files/supervisor-vrouter.initd
+++ b/common/control_files/supervisor-vrouter.initd
@@ -32,6 +32,17 @@ function daemon_start() {
      /etc/contrail/vnagent_ExecStartPost.sh
      RETVAL=$?
      [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
+     if [ $RETVAL -ne 0 ]; then
+        echo "supervisor-vrouter start on port 9005 failed. checking lsof.."
+        lsof -i :9005
+        if [ $? -eq 0 ]; then
+            echo "Another program listening on 9005"
+            pid=`lsof -Fp -i :9005 | cut -f2 -d'p'`
+            if [ "x$pid" != "x" ] ; then
+                ps uw -p $pid
+            fi
+        fi
+     fi
 }
 
 function daemon_stop() {
diff --git a/common/control_files/supervisor-webui.initd b/common/control_files/supervisor-webui.initd
--- a/common/control_files/supervisor-webui.initd
+++ b/common/control_files/supervisor-webui.initd
@@ -30,6 +30,17 @@ function daemon_start() {
      /usr/bin/supervisord -c /etc/contrail/supervisord_webui.conf
      RETVAL=$?
      [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
+     if [ $RETVAL -ne 0 ]; then
+        echo "supervisor-analytics start on port 9008 failed. checking lsof.."
+        lsof -i :9008
+        if [ $? -eq 0 ]; then
+            echo "Another program listening on 9008"
+            pid=`lsof -Fp -i :9008 | cut -f2 -d'p'`
+            if [ "x$pid" != "x" ] ; then
+                ps uw -p $pid
+            fi
+        fi
+     fi
 }
 
 function daemon_stop() {
