when contrail-openstack-database postinst script is run, it seems cassandra hasn't started by then and run of the postinst becomes a no-op.
Change-Id: I58e23e2b472788b2d13addc4cca473f2c70e3000
Closes-Bug: #1608806
(cherry picked from commit 78c6c3cb7d7a18ac7c5a9993cac7e2e073c88581)

diff --git a/common/debian/contrail-openstack-database/debian/contrail-openstack-database.postinst b/common/debian/contrail-openstack-database/debian/contrail-openstack-database.postinst
--- a/common/debian/contrail-openstack-database/debian/contrail-openstack-database.postinst
+++ b/common/debian/contrail-openstack-database/debian/contrail-openstack-database.postinst
@@ -3,7 +3,33 @@
 if [ "$1" = "configure" ]; then
     echo "Running Postinst for contrail-openstack-database install.."
     if [ -z "$2" ]; then
+        i=0
+        while : ; do
+            sudo service cassandra status
+            if [ $? -eq 0 ] ; then
+                break
+            fi
+            i=$(($i+1))
+            if [ $i -gt 10 ] ; then
+                echo "Error: postinst contrail-openstack-database, expected cassandra to be running"
+                break
+            fi
+            sleep 3
+        done
         sudo service cassandra stop
+        i=0
+        while : ; do
+            ps auxw | grep -Eq "Dcassandra-pidfile=.*cassandra\.pid" 2>/dev/null
+            if [ $? -ne 0 ] ; then
+                break
+            fi
+            i=$(($i+1))
+            if [ $i -gt 5 ] ; then
+                kill `ps auxw | grep -E "Dcassandra-pidfile=.*cassandra\.pid" | grep -v grep | awk '{print $2}'` > /dev/null 2>&1
+                break
+            fi
+            sleep 2
+        done
         sudo rm -rf /var/lib/cassandra
     fi
     sudo update-rc.d cassandra disable
